"""
Interactive setup command for JiraJitsu
"""
import click
from rich.console import Console
from rich.prompt import Prompt, Confirm
import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

console = Console()


@click.command()
@click.pass_context
def setup(ctx):
    """
    Interactive setup wizard for JiraJitsu

    Configure JIRA and JitBit connections, directories, and settings.
    """

    console.print("[bold blue]JiraJitsu Interactive Setup[/bold blue]\n")
    console.print("This wizard will help you configure JiraJitsu for first-time use.\n")

    # Determine paths
    base_dir = Path(__file__).parent.parent.parent
    env_path = base_dir / '.env'
    config_dir = base_dir / 'config'
    config_path = config_dir / 'config.yml'

    # Check if already configured
    if env_path.exists() and config_path.exists():
        console.print("[yellow]Configuration files already exist[/yellow]")
        if not Confirm.ask("Overwrite existing configuration?", default=False):
            console.print("[yellow]Setup cancelled[/yellow]")
            return

    console.print()

    # Collect JIRA configuration
    console.print("[bold cyan]JIRA Configuration[/bold cyan]")
    jira_url = Prompt.ask("JIRA API URL", default="https://your-jira.com/rest/api/2")
    jira_user = Prompt.ask("JIRA Username")
    jira_pwd = Prompt.ask("JIRA Password", password=True)
    jira_filter_id = Prompt.ask("JIRA Filter ID for migration", default="10000")
    jira_tag_field = Prompt.ask("JIRA custom field for tags", default="customfield_10800")

    console.print()

    # Collect JitBit configuration
    console.print("[bold cyan]JitBit Configuration[/bold cyan]")
    jitbit_url = Prompt.ask("JitBit API URL", default="https://your-company.jitbit.com/helpdesk/api")
    jitbit_user = Prompt.ask("JitBit Username")
    jitbit_pwd = Prompt.ask("JitBit Password", password=True)
    jitbit_category = Prompt.ask("JitBit migration category ID", default="10000")
    jitbit_delete_category = Prompt.ask("JitBit deleted items category ID (optional)", default="")
    jitbit_default_email = Prompt.ask("Default assignee email", default="admin@yourcompany.com")

    console.print()

    # Collect directory configuration
    console.print("[bold cyan]Directory Configuration[/bold cyan]")
    attachment_folder = Prompt.ask("Attachment storage folder", default=str(base_dir / "attachments"))
    log_dir = Prompt.ask("Log directory", default=str(base_dir / "logs"))

    # Attachment fetch mode
    fetch_mode = Prompt.ask(
        "Attachment fetch mode",
        choices=["NEW_ONLY", "DELETE_REFETCH"],
        default="NEW_ONLY"
    )

    console.print()

    # Create directories
    console.print("[cyan]Creating directories...[/cyan]")
    Path(attachment_folder).mkdir(parents=True, exist_ok=True)
    Path(log_dir).mkdir(parents=True, exist_ok=True)
    config_dir.mkdir(parents=True, exist_ok=True)
    console.print("[green]✓ Directories created[/green]\n")

    # Write .env file
    console.print("[cyan]Writing .env file...[/cyan]")
    env_content = f"""# JiraJitsu Environment Configuration
# Generated by setup wizard

# JitBit API Credentials
JITBIT_API_URL={jitbit_url}
JITBIT_USER={jitbit_user}
JITBIT_PWD={jitbit_pwd}

# JIRA API Credentials
JIRA_API_URL={jira_url}
JIRA_USER={jira_user}
JIRA_PWD={jira_pwd}
"""

    with open(env_path, 'w') as f:
        f.write(env_content)

    console.print(f"[green]✓ Created {env_path}[/green]\n")

    # Write config.yml file
    console.print("[cyan]Writing config.yml file...[/cyan]")
    config_content = f"""# JiraJitsu Configuration File
# Generated by setup wizard

# Logging Configuration
log_dir: {log_dir}
log_max_bytes: 10485760
log_backup_count: 5

# JitBit Settings
jitbit_migrate_category_id: {jitbit_category}
{f'jitbit_delete_category_id: {jitbit_delete_category}' if jitbit_delete_category else '# jitbit_delete_category_id: 12346'}
jitbit_default_assign_email: {jitbit_default_email}

# JIRA Settings
jira_filter_id: {jira_filter_id}
jira_tag_field: {jira_tag_field}

# Attachment Settings
fetch_attachments: {fetch_mode}
attachment_folder: {attachment_folder}
"""

    with open(config_path, 'w') as f:
        f.write(config_content)

    console.print(f"[green]✓ Created {config_path}[/green]\n")

    # Test connections
    if Confirm.ask("Test API connections now?", default=True):
        console.print("\n[cyan]Testing connections...[/cyan]\n")

        # Import here to use new config
        try:
            # Reload config module to pick up new settings
            import importlib
            from jirajitsu import config as cfg
            importlib.reload(cfg)

            from jirajitsu.jira_api import JiraApi
            from jirajitsu.jitbit_api import JitbitApi
            from jirajitsu.log_handler import LogHandler

            LogHandler(log_level='INFO')

            # Test JIRA
            console.print("[cyan]Testing JIRA connection...[/cyan]")
            jira_api = JiraApi()
            if jira_api.check_url_and_user():
                console.print("[green]✓ JIRA connection successful[/green]")
            else:
                console.print("[red]✗ JIRA connection failed[/red]")

            # Test JitBit
            console.print("[cyan]Testing JitBit connection...[/cyan]")
            jitbit_api = JitbitApi()
            if jitbit_api.check_url_and_user():
                console.print("[green]✓ JitBit connection successful[/green]")
            else:
                console.print("[red]✗ JitBit connection failed[/red]")

        except Exception as e:
            console.print(f"[red]Error testing connections: {str(e)}[/red]")
            console.print("[yellow]You can run 'jirajitsu validate config' later to test[/yellow]")

    console.print("\n[bold green]✓ Setup complete![/bold green]")
    console.print("\nNext steps:")
    console.print("  1. Run 'jirajitsu validate config' to verify configuration")
    console.print("  2. Run 'jirajitsu list projects' to see available projects")
    console.print("  3. Run 'jirajitsu validate users' to check user mappings")
    console.print("  4. Run 'jirajitsu test --issue ISSUE-KEY' to test migration")
    console.print("  5. Run 'jirajitsu migrate' to start full migration")
